Import Libraries

In [1]:
!pip install beautifulsoup4
import requests
import pandas as pd
import re
from bs4 import BeautifulSoup

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

In [22]:
##scraping the info of all IT job listed in bdjobs.com

URL = "https://jobs.bdjobs.com/jobsearch.asp?fcatId=8&icatId="
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")

Create a Dataframe

In [23]:
columns = ['Job Position', 'Company', 'Location', 'Education', 'Experience', 'Deadline']
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [Job Position, Company, Location, Education, Experience, Deadline]
Index: []

Parse the HTML and Save the Job Info in the DF

In [24]:
title = soup.find_all("div", class_='job-title-text')

company = soup.find_all("div", class_='comp-name-text')

location = soup.find_all("div", class_='locon-text')

education = soup.find_all("div", class_='edu-text')

experience = soup.find_all("div", class_='exp-text')

deadline = soup.find_all("div", class_='dead-text')


pattern = "[\d]{1,2}\ [A-Z][a-z]+\ [\d]{4}" ##for deadline

for idx,value in enumerate(zip(title,company,location,education,experience,deadline)):

  df.loc[len(df.index)] = [value[0].find('a').text.strip(), value[1].get_text().strip(), value[2].get_text().strip(), value[3].get_text().strip(), value[4].get_text().strip(), re.findall(pattern, value[5].get_text().strip())[0]]

In [25]:
df

,Job Position,Company,Location,Education,Experience,Deadline
0,Network Administrator (Contact Center Solution),Walton Hi-Tech Industries Ltd.,Dhaka,M.Sc or B.Sc in CSE/EEE/ICT/ETE from any reput...,3 to 5 year(s),27 May 2022
1,Android Application Developer,SIMEC System Limited,Uttara,Bachelor of Science (BSc) in Computer Science ...,2 to 5 year(s),27 May 2022
2,System Engineer (Support),hSenid Mobile Solutions (Bangladesh) Pvt Ltd,Anywhere in Bangladesh,Bachelor of Computer Application (BCA)Degree i...,0 to 2 year(s),27 May 2022
3,Digital Marketing Executive (Lead Generation),Genex Holding,Mirpur,Education qualification will be relaxed for Ex...,At least 2 year(s),27 May 2022
4,IT Help Desk Junior Officer,Scholastica Ltd. (A Concern of ASCENT Group),Dhaka,B. Sc in computer science,1 to 2 year(s),6 May 2022
5,Executive- IT,Best Tex International Limited,Uttara,Bachelor of Science (BSc) in B. Sc. in C.S.E f...,2 to 3 year(s),27 May 2022
6,Computer Science Engineer (CSE),UK-Bangla Network Ltd,Anywhere in Bangladesh,B.Sc./M.Sc (CSE) in Software engineering from ...,2 to 3 year(s),27 May 2022
7,"Electrical, Electronics & Tele-communication E...",UK-Bangla Network Ltd,Anywhere in Bangladesh,B.Sc./M.Sc (CSE) in Software engineering from ...,2 to 3 year(s),27 May 2022
8,SEO Expert,Akaar IT Ltd.,Uttara,HSC,1 to 2 year(s),26 May 2022
9,Senior C# and C++ Developer,BJIT Ltd.,Dhaka,Bachelor of Science (BSc) in Computer Science ...,4 to 6 year(s),26 May 2022
10,Front End Developer,INTELLI Global Services,Gulshan,Bachelor`s degree in any disciplineSkills Requ...,At least 2 year(s),26 May 2022
11,Full-Stack Developer,INTELLI Global Services,Gulshan,Bachelor’s/Master’s degree in Computer Science...,At least 3 year(s),26 May 2022
12,Software Project Manager (Data Science),BYSL Global Technology Group,Gulshan,"Bachelor’s degree in Computer Science, Enginee...",At least 7 year(s),26 May 2022
13,Backend Developer (Node.js),INTELLI Global Services,Gulshan,Bachelor’s/Master’s degree in Computer Science...,At least 3 year(s),26 May 2022
14,Augmented & Virtual Reality (AR/VR) Developer,INTELLI Global Services,Gulshan,BS / MS in Computer Science or equivalent degr...,Na,26 May 2022
15,Backend Game Developer,INTELLI Global Services,Gulshan,"MS/BS in Computer Science, IT, or equivalent d...",At least 5 year(s),26 May 2022
16,Game Developer,INTELLI Global Services,Gulshan,"MS/BS in Computer Science, IT, or equivalent d...",At least 5 year(s),26 May 2022
17,Technical Support Engineer,BDCOM Online Limited,"Dhaka,Jamalpur",Bachelor of Science (BSc) in Computer Science ...,0 to 2 year(s),26 May 2022